services:
   vprodb:
      build:
         context: /home/ubuntu/vprofile-project/Docker-files/db
      image: royrishwanth/vprofiledb
      container_name: vprodb
      ports:
        - "3306:3306"
      volumes:
        - vprodbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=vprodbpass

   vproache01:
      image: memcached
      container_name: vprocache01
      ports:
        - "11211:11211"

   vprormq01:
      image: rabbitmq
      container_name: vprormq01
      ports:
        - 5672:5672
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest

   vproapp:
      build:
         context: /home/ubuntu/vprofile-project/Docker-files/app
      image: royrishwanth/vprofileapp
      container_name: vproapp
      ports:
        - "8080:8080"
      volumes:
        - vproappdata:/usr/local/tomcat/webapps
      environment:
        - MYSQL_ROOT_PASSWORD=vprodbpass

   vproweb:
      build:
         context: /home/ubuntu/vprofile-project/Docker-files/web
      image: royrishwanth/vprofileweb
      container_name: vproweb
      ports:
        - "80:80"
      

volumes:
  vprodbdata: {}
  vproappdata: {}

